#ifndef __INCLUDE_OBJ_H__
#define __INCLUDE_OBJ_H__

#if !defined(__cplusplus)
#error C++ compiler required
#endif

#include <afxdisp.h>
#include <objbase.h>
#include "atlbase.h"
#include <atlstr.h>
#include <string>

using wstring = std::wstring;
//#define _AFXDLL
class dmsoft
{
private:

public:
	IDispatch* obj;
	dmsoft();
	virtual ~dmsoft();

	virtual wstring Ver();
	virtual long SetPath(const wstring path);
	//virtual long SetPath(std::wstring path);
	virtual wstring Ocr(long x1, long y1, long x2, long y2, const wstring color, double sim);
	virtual std::tuple<bool,int,int> FindStr(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim);
	virtual long GetResultCount(const wstring str);
	virtual std::tuple<long, int, int> GetResultPos(const wstring str, long index);
	virtual long StrStr(const wstring s, const wstring str);
	virtual long SendCommand(const wstring cmd);
	virtual long UseDict(long index);
	virtual wstring GetBasePath();
	virtual long SetDictPwd(const wstring pwd);
	virtual wstring OcrInFile(long x1, long y1, long x2, long y2, const wstring pic_name, const wstring color, double sim);
	virtual long Capture(long x1, long y1, long x2, long y2, const wstring file_name);
	virtual long KeyPress(long vk);
	virtual long KeyDown(long vk);
	virtual long KeyUp(long vk);
	virtual long LeftClick();
	virtual long RightClick();
	virtual long MiddleClick();
	virtual long LeftDoubleClick();
	virtual long LeftDown();
	virtual long LeftUp();
	virtual long RightDown();
	virtual long RightUp();
	virtual long MoveTo(long x, long y);
	virtual long MoveR(long rx, long ry);
	virtual wstring GetColor(long x, long y);
	virtual wstring GetColorBGR(long x, long y);
	virtual wstring RGB2BGR(const wstring rgb_color);
	virtual wstring BGR2RGB(const wstring bgr_color);
	virtual long UnBindWindow();
	virtual long CmpColor(long x, long y, const wstring color, double sim);
	virtual  std::tuple<long, int, int> ClientToScreen(long hwnd, long x, long y);
	virtual  std::tuple<long, int, int> ScreenToClient(long hwnd, long x, long y);
	virtual long ShowScrMsg(long x1, long y1, long x2, long y2, const wstring msg, const wstring color);
	virtual long SetMinRowGap(long row_gap);
	virtual long SetMinColGap(long col_gap);
	virtual  std::tuple<long, int, int> FindColor(long x1, long y1, long x2, long y2, const wstring color, double sim, long dir);
	virtual wstring FindColorEx(long x1, long y1, long x2, long y2, const wstring color, double sim, long dir);
	virtual long SetWordLineHeight(long line_height);
	virtual long SetWordGap(long word_gap);
	virtual long SetRowGapNoDict(long row_gap);
	virtual long SetColGapNoDict(long col_gap);
	virtual long SetWordLineHeightNoDict(long line_height);
	virtual long SetWordGapNoDict(long word_gap);
	virtual long GetWordResultCount(const wstring str);
	virtual  std::tuple<long, int, int> GetWordResultPos(const wstring str, long index);
	virtual wstring GetWordResultStr(const wstring str, long index);
	virtual wstring GetWords(long x1, long y1, long x2, long y2, const wstring color, double sim);
	virtual wstring GetWordsNoDict(long x1, long y1, long x2, long y2, const wstring color);
	virtual long SetShowErrorMsg(long show);
	virtual std::tuple<long, int, int> GetClientSize(long hwnd);
	virtual long MoveWindow(long hwnd, long x, long y);
	virtual wstring GetColorHSV(long x, long y);
	virtual wstring GetAveRGB(long x1, long y1, long x2, long y2);
	virtual wstring GetAveHSV(long x1, long y1, long x2, long y2);
	virtual long GetForegroundWindow();
	virtual long GetForegroundFocus();
	virtual long GetMousePointWindow();
	virtual long GetPointWindow(long x, long y);
	virtual wstring EnumWindow(long parent, const wstring title, const wstring class_name, long filter);
	virtual long GetWindowState(long hwnd, long flag);
	virtual long GetWindow(long hwnd, long flag);
	virtual long GetSpecialWindow(long flag);
	virtual long SetWindowText(long hwnd, const wstring text);
	virtual long SetWindowSize(long hwnd, long width, long height);
	virtual std::tuple<long, int, int,int,int> GetWindowRect(long hwnd);
	virtual wstring GetWindowTitle(long hwnd);
	virtual wstring GetWindowClass(long hwnd);
	virtual long SetWindowState(long hwnd, long flag);
	virtual long CreateFoobarRect(long hwnd, long x, long y, long w, long h);
	virtual long CreateFoobarRoundRect(long hwnd, long x, long y, long w, long h, long rw, long rh);
	virtual long CreateFoobarEllipse(long hwnd, long x, long y, long w, long h);
	virtual long CreateFoobarCustom(long hwnd, long x, long y, const wstring pic, const wstring trans_color, double sim);
	virtual long FoobarFillRect(long hwnd, long x1, long y1, long x2, long y2, const wstring color);
	virtual long FoobarDrawText(long hwnd, long x, long y, long w, long h, const wstring text, const wstring color, long align);
	virtual long FoobarDrawPic(long hwnd, long x, long y, const wstring pic, const wstring trans_color);
	virtual long FoobarUpdate(long hwnd);
	virtual long FoobarLock(long hwnd);
	virtual long FoobarUnlock(long hwnd);
	virtual long FoobarSetFont(long hwnd, const wstring font_name, long size, long flag);
	virtual long FoobarTextRect(long hwnd, long x, long y, long w, long h);
	virtual long FoobarPrintText(long hwnd, const wstring text, const wstring color);
	virtual long FoobarClearText(long hwnd);
	virtual long FoobarTextLineGap(long hwnd, long gap);
	virtual long Play(const wstring file_name);
	virtual long FaqCapture(long x1, long y1, long x2, long y2, long quality, long delay, long time);
	virtual long FaqRelease(long handle);
	virtual wstring FaqSend(const wstring server, long handle, long request_type, long time_out);
	virtual long Beep(long fre, long delay);
	virtual long FoobarClose(long hwnd);
	virtual long MoveDD(long dx, long dy);
	virtual long FaqGetSize(long handle);
	virtual long LoadPic(const wstring pic_name);
	virtual long FreePic(const wstring pic_name);
	virtual long GetScreenData(long x1, long y1, long x2, long y2);
	virtual long FreeScreenData(long handle);
	virtual long WheelUp();
	virtual long WheelDown();
	virtual long SetMouseDelay(const wstring tpe, long delay);
	virtual long SetKeypadDelay(const wstring tpe, long delay);
	virtual wstring GetEnv(long index, const wstring name);
	virtual long SetEnv(long index, const wstring name, const wstring value);
	virtual long SendString(long hwnd, const wstring str);
	virtual long DelEnv(long index, const wstring name);
	virtual wstring GetPath();
	virtual long SetDict(long index, const wstring dict_name);
	virtual std::tuple<bool,int,int> FindPic(long x1, long y1, long x2, long y2, const wstring pic_name, const wstring delta_color, double sim, long dir);
	virtual wstring FindPicEx(long x1, long y1, long x2, long y2, const wstring pic_name, const wstring delta_color, double sim, long dir);
	virtual long SetClientSize(long hwnd, long width, long height);
	virtual long ReadInt(long hwnd, const wstring addr, long tpe);
	virtual float ReadFloat(long hwnd, const wstring addr);
	virtual double ReadDouble(long hwnd, const wstring addr);
	virtual wstring FindInt(long hwnd, const wstring addr_range, long int_value_min, long int_value_max, long tpe);
	virtual wstring FindFloat(long hwnd, const wstring addr_range, float float_value_min, float float_value_max);
	virtual wstring FindDouble(long hwnd, const wstring addr_range, double double_value_min, double double_value_max);
	virtual wstring FindString(long hwnd, const wstring addr_range, const wstring string_value, long tpe);
	virtual long GetModuleBaseAddr(long hwnd, const wstring module_name);
	virtual wstring MoveToEx(long x, long y, long w, long h);
	virtual wstring MatchPicName(const wstring pic_name);
	virtual long AddDict(long index, const wstring dict_info);
	virtual long EnterCri();
	virtual long LeaveCri();
	virtual long WriteInt(long hwnd, const wstring addr, long tpe, long v);
	virtual long WriteFloat(long hwnd, const wstring addr, float v);
	virtual long WriteDouble(long hwnd, const wstring addr, double v);
	virtual long WriteString(long hwnd, const wstring addr, long tpe, const wstring v);
	virtual long AsmAdd(const wstring asm_ins);
	virtual long AsmClear();
	virtual long AsmCall(long hwnd, long mode);
	virtual std::tuple<long, int, int> FindMultiColor(long x1, long y1, long x2, long y2, const wstring first_color, const wstring offset_color, double sim, long dir);
	virtual wstring FindMultiColorEx(long x1, long y1, long x2, long y2, const wstring first_color, const wstring offset_color, double sim, long dir);
	virtual wstring AsmCode(long base_addr);
	virtual wstring Assemble(const wstring asm_code, long base_addr, long is_upper);
	virtual long SetWindowTransparent(long hwnd, long v);
	virtual wstring ReadData(long hwnd, const wstring addr, long length);
	virtual long WriteData(long hwnd, const wstring addr, const wstring data);
	virtual wstring FindData(long hwnd, const wstring addr_range, const wstring data);
	virtual long SetPicPwd(const wstring pwd);
	virtual long Log(const wstring info);
	virtual wstring FindStrE(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim);
	virtual wstring FindColorE(long x1, long y1, long x2, long y2, const wstring color, double sim, long dir);
	virtual wstring FindPicE(long x1, long y1, long x2, long y2, const wstring pic_name, const wstring delta_color, double sim, long dir);
	virtual wstring FindMultiColorE(long x1, long y1, long x2, long y2, const wstring first_color, const wstring offset_color, double sim, long dir);
	virtual long SetExactOcr(long exact_ocr);
	virtual wstring ReadString(long hwnd, const wstring addr, long tpe, long length);
	virtual long FoobarTextPrintDir(long hwnd, long dir);
	virtual wstring OcrEx(long x1, long y1, long x2, long y2, const wstring color, double sim);
	virtual long SetDisplayInput(const wstring mode);
	virtual long GetTime();
	virtual long GetScreenWidth();
	virtual long GetScreenHeight();
	virtual long BindWindowEx(long hwnd, const wstring display, const wstring mouse, const wstring keypad, const wstring public_desc, long mode);
	virtual wstring GetDiskSerial();
	virtual wstring Md5(const wstring str);
	virtual wstring GetMac();
	virtual long ActiveInputMethod(long hwnd, const wstring id);
	virtual long CheckInputMethod(long hwnd, const wstring id);
	virtual long FindInputMethod(const wstring id);
	virtual std::tuple<long, int, int> GetCursorPos();
	virtual long BindWindow(long hwnd, const wstring display, const wstring mouse, const wstring keypad, long mode);
	virtual long FindWindow(const wstring class_name, const wstring title_name);
	virtual long GetScreenDepth();
	virtual long SetScreen(long width, long height, long depth);
	virtual long ExitOs(long tpe);
	virtual wstring GetDir(long tpe);
	virtual long GetOsType();
	virtual long FindWindowEx(long parent, const wstring class_name, const wstring title_name);
	virtual long SetExportDict(long index, const wstring dict_name);
	virtual wstring GetCursorShape();
	virtual long DownCpu(long rate);
	virtual wstring GetCursorSpot();
	virtual long SendString2(long hwnd, const wstring str);
	virtual long FaqPost(const wstring server, long handle, long request_type, long time_out);
	virtual wstring FaqFetch();
	virtual wstring FetchWord(long x1, long y1, long x2, long y2, const wstring color, const wstring word);
	virtual long CaptureJpg(long x1, long y1, long x2, long y2, const wstring file_name, long quality);
	virtual std::tuple<long, int, int> FindStrWithFont(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim, const wstring font_name, long font_size, long flag);
	virtual wstring FindStrWithFontE(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim, const wstring font_name, long font_size, long flag);
	virtual wstring FindStrWithFontEx(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim, const wstring font_name, long font_size, long flag);
	virtual wstring GetDictInfo(const wstring str, const wstring font_name, long font_size, long flag);
	virtual long SaveDict(long index, const wstring file_name);
	virtual long GetWindowProcessId(long hwnd);
	virtual wstring GetWindowProcessPath(long hwnd);
	virtual long LockInput(long locks);
	virtual wstring GetPicSize(const wstring pic_name);
	virtual long GetID();
	virtual long CapturePng(long x1, long y1, long x2, long y2, const wstring file_name);
	virtual long CaptureGif(long x1, long y1, long x2, long y2, const wstring file_name, long delay, long time);
	virtual long ImageToBmp(const wstring pic_name, const wstring bmp_name);
	virtual std::tuple<long, int, int> FindStrFast(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim);
	virtual wstring FindStrFastEx(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim);
	virtual wstring FindStrFastE(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim);
	virtual long EnableDisplayDebug(long enable_debug);
	virtual long CapturePre(const wstring file_name);
	virtual long RegEx(const wstring code, const wstring Ver, const wstring ip);
	virtual wstring GetMachineCode();
	virtual long SetClipboard(const wstring data);
	virtual wstring GetClipboard();
	virtual long GetNowDict();
	virtual long Is64Bit();
	virtual long GetColorNum(long x1, long y1, long x2, long y2, const wstring color, double sim);
	virtual wstring EnumWindowByProcess(const wstring process_name, const wstring title, const wstring class_name, long filter);
	virtual long GetDictCount(long index);
	virtual long GetLastError();
	virtual wstring GetNetTime();
	virtual long EnableGetColorByCapture(long en);
	virtual long CheckUAC();
	virtual long SetUAC(long uac);
	virtual long DisableFontSmooth();
	virtual long CheckFontSmooth();
	virtual long SetDisplayAcceler(long level);
	virtual long FindWindowByProcess(const wstring process_name, const wstring class_name, const wstring title_name);
	virtual long FindWindowByProcessId(long process_id, const wstring class_name, const wstring title_name);
	virtual wstring ReadIni(const wstring section, const wstring key, const wstring file_name);
	virtual long WriteIni(const wstring section, const wstring key, const wstring v, const wstring file_name);
	virtual long RunApp(const wstring path, long mode);
	virtual long Delay(long mis);
	virtual long FindWindowSuper(const wstring spec1, long flag1, long type1, const wstring spec2, long flag2, long type2);
	virtual wstring ExcludePos(const wstring all_pos, long tpe, long x1, long y1, long x2, long y2);
	virtual wstring FindNearestPos(const wstring all_pos, long tpe, long x, long y);
	virtual wstring SortPosDistance(const wstring all_pos, long tpe, long x, long y);
	virtual long FindPicMem(long x1, long y1, long x2, long y2, const wstring pic_info, const wstring delta_color, double sim, long dir, long* x, long* y);
	virtual wstring FindPicMemEx(long x1, long y1, long x2, long y2, const wstring pic_info, const wstring delta_color, double sim, long dir);
	virtual wstring FindPicMemE(long x1, long y1, long x2, long y2, const wstring pic_info, const wstring delta_color, double sim, long dir);
	virtual wstring AppendPicAddr(const wstring pic_info, long addr, long size);
	virtual long WriteFile(const wstring file_name, const wstring content);
	virtual long Stop(long id);
	virtual long SetDictMem(long index, long addr, long size);
	virtual wstring GetNetTimeSafe();
	virtual long ForceUnBindWindow(long hwnd);
	virtual wstring ReadIniPwd(const wstring section, const wstring key, const wstring file_name, const wstring pwd);
	virtual long WriteIniPwd(const wstring section, const wstring key, const wstring v, const wstring file_name, const wstring pwd);
	virtual long DecodeFile(const wstring file_name, const wstring pwd);
	virtual long KeyDownChar(const wstring key_str);
	virtual long KeyUpChar(const wstring key_str);
	virtual long KeyPressChar(const wstring key_str);
	virtual long KeyPressStr(const wstring key_str, long delay);
	virtual long EnableKeypadPatch(long en);
	virtual long EnableKeypadSync(long en, long time_out);
	virtual long EnableMouseSync(long en, long time_out);
	virtual long DmGuard(long en, const wstring tpe);
	virtual long FaqCaptureFromFile(long x1, long y1, long x2, long y2, const wstring file_name, long quality);
	virtual wstring FindIntEx(long hwnd, const wstring addr_range, long int_value_min, long int_value_max, long tpe, long steps, long multi_thread, long mode);
	virtual wstring FindFloatEx(long hwnd, const wstring addr_range, float float_value_min, float float_value_max, long steps, long multi_thread, long mode);
	virtual wstring FindDoubleEx(long hwnd, const wstring addr_range, double double_value_min, double double_value_max, long steps, long multi_thread, long mode);
	virtual wstring FindStringEx(long hwnd, const wstring addr_range, const wstring string_value, long tpe, long steps, long multi_thread, long mode);
	virtual wstring FindDataEx(long hwnd, const wstring addr_range, const wstring data, long steps, long multi_thread, long mode);
	virtual long EnableRealMouse(long en, long mousedelay, long mousestep);
	virtual long EnableRealKeypad(long en);
	virtual long SendStringIme(const wstring str);
	virtual long FoobarDrawLine(long hwnd, long x1, long y1, long x2, long y2, const wstring color, long style, long width);
	virtual wstring FindStrEx(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim);
	virtual long IsBind(long hwnd);
	virtual long SetDisplayDelay(long t);
	virtual long GetDmCount();
	virtual long DisableScreenSave();
	virtual long DisablePowerSave();
	virtual long SetMemoryHwndAsProcessId(long en);
	virtual long FindShape(long x1, long y1, long x2, long y2, const wstring offset_color, double sim, long dir, long* x, long* y);
	virtual wstring FindShapeE(long x1, long y1, long x2, long y2, const wstring offset_color, double sim, long dir);
	virtual wstring FindShapeEx(long x1, long y1, long x2, long y2, const wstring offset_color, double sim, long dir);
	virtual wstring FindStrS(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim, long* x, long* y);
	virtual wstring FindStrExS(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim);
	virtual wstring FindStrFastS(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim, long* x, long* y);
	virtual wstring FindStrFastExS(long x1, long y1, long x2, long y2, const wstring str, const wstring color, double sim);
	virtual wstring FindPicS(long x1, long y1, long x2, long y2, const wstring pic_name, const wstring delta_color, double sim, long dir, long* x, long* y);
	virtual wstring FindPicExS(long x1, long y1, long x2, long y2, const wstring pic_name, const wstring delta_color, double sim, long dir);
	virtual long ClearDict(long index);
	virtual wstring GetMachineCodeNoMac();
	virtual std::tuple<long,int,int,int,int> GetClientRect(long hwnd);
	virtual long EnableFakeActive(long en);
	virtual long GetScreenDataBmp(long x1, long y1, long x2, long y2, long* data, long* size);
	virtual long EncodeFile(const wstring file_name, const wstring pwd);
	virtual wstring GetCursorShapeEx(long tpe);
	virtual long FaqCancel();
	virtual wstring IntToData(long int_value, long tpe);
	virtual wstring FloatToData(float float_value);
	virtual wstring DoubleToData(double double_value);
	virtual wstring StringToData(const wstring string_value, long tpe);
	virtual long SetMemoryFindResultToFile(const wstring file_name);
	virtual long EnableBind(long en);
	virtual long SetSimMode(long mode);
	virtual long LockMouseRect(long x1, long y1, long x2, long y2);
	virtual long SendPaste(long hwnd);
	virtual long IsDisplayDead(long x1, long y1, long x2, long y2, long t);
	virtual long GetKeyState(long vk);
	virtual long CopyFile(const wstring src_file, const wstring dst_file, long over);
	virtual long IsFileExist(const wstring file_name);
	virtual long DeleteFile(const wstring file_name);
	virtual long MoveFile(const wstring src_file, const wstring dst_file);
	virtual long CreateFolder(const wstring folder_name);
	virtual long DeleteFolder(const wstring folder_name);
	virtual long GetFileLength(const wstring file_name);
	virtual wstring ReadFile(const wstring file_name);
	virtual long WaitKey(long key_code, long time_out);
	virtual long DeleteIni(const wstring section, const wstring key, const wstring file_name);
	virtual long DeleteIniPwd(const wstring section, const wstring key, const wstring file_name, const wstring pwd);
	virtual long EnableSpeedDx(long en);
	virtual long EnableIme(long en);
	virtual long Reg(const wstring code, const wstring Ver);
	virtual wstring SelectFile();
	virtual wstring SelectDirectory();
	virtual long LockDisplay(long locks);
	virtual long FoobarSetSave(long hwnd, const wstring file_name, long en, const wstring header);
	virtual wstring EnumWindowSuper(const wstring spec1, long flag1, long type1, const wstring spec2, long flag2, long type2, long sort);
	virtual long DownloadFile(const wstring url, const wstring save_file, long timeout);
	virtual long EnableKeypadMsg(long en);
	virtual long EnableMouseMsg(long en);
	virtual long RegNoMac(const wstring code, const wstring Ver);
	virtual long RegExNoMac(const wstring code, const wstring Ver, const wstring ip);
	virtual long SetEnumWindowDelay(long delay);
	virtual long FindMulColor(long x1, long y1, long x2, long y2, const wstring color, double sim);
	virtual wstring GetDict(long index, long font_index);
	virtual long GetBindWindow();
	virtual long FoobarStartGif(long hwnd, long x, long y, const wstring pic_name, long repeat_limit, long delay);
	virtual long FoobarStopGif(long hwnd, long x, long y, const wstring pic_name);
	virtual long FreeProcessMemory(long hwnd);
	virtual wstring ReadFileData(const wstring file_name, long start_pos, long end_pos);
	virtual long VirtualAllocEx(long hwnd, long addr, long size, long tpe);
	virtual long VirtualFreeEx(long hwnd, long addr);
	virtual wstring GetCommandLine(long hwnd);
	virtual long TerminateProcess(long pid);
	virtual wstring GetNetTimeByIp(const wstring ip);
	virtual wstring EnumProcess(const wstring name);
	virtual wstring GetProcessInfo(long pid);
	virtual long ReadIntAddr(long hwnd, long addr, long tpe);
	virtual wstring ReadDataAddr(long hwnd, long addr, long length);
	virtual double ReadDoubleAddr(long hwnd, long addr);
	virtual float ReadFloatAddr(long hwnd, long addr);
	virtual wstring ReadStringAddr(long hwnd, long addr, long tpe, long length);
	virtual long WriteDataAddr(long hwnd, long addr, const wstring data);
	virtual long WriteDoubleAddr(long hwnd, long addr, double v);
	virtual long WriteFloatAddr(long hwnd, long addr, float v);
	virtual long WriteIntAddr(long hwnd, long addr, long tpe, long v);
	virtual long WriteStringAddr(long hwnd, long addr, long tpe, const wstring v);
	//virtual long Delays(double min_s, double max_s);
	virtual long Delays(long min_s, long max_s);
	virtual long FindColorBlock(long x1, long y1, long x2, long y2, const wstring color, double sim, long count, long width, long height, long* x, long* y);
	virtual wstring FindColorBlockEx(long x1, long y1, long x2, long y2, const wstring color, double sim, long count, long width, long height);
	virtual long OpenProcess(long pid);
	virtual wstring EnumIniSection(const wstring file_name);
	virtual wstring EnumIniSectionPwd(const wstring file_name, const wstring pwd);
	virtual wstring EnumIniKey(const wstring section, const wstring file_name);
	virtual wstring EnumIniKeyPwd(const wstring section, const wstring file_name, const wstring pwd);
	virtual long SwitchBindWindow(long hwnd);
	virtual long InitCri();
	virtual long SendStringIme2(long hwnd, const wstring str, long mode);
	virtual wstring EnumWindowByProcessId(long pid, const wstring title, const wstring class_name, long filter);
	virtual wstring GetDisplayInfo();
	virtual long EnableFontSmooth();
	virtual wstring OcrExOne(long x1, long y1, long x2, long y2, const wstring color, double sim);
	virtual long SetAero(long en);
	virtual long FoobarSetTrans(long hwnd, long trans, const wstring color, double sim);
	virtual long EnablePicCache(long en);
	virtual wstring GetInfo(const wstring cmd, const wstring param);
	virtual long FaqIsPosted();
	virtual long LoadPicByte(long addr, long size, const wstring name);
	virtual long MiddleDown();
	virtual long MiddleUp();
	virtual long FaqCaptureString(const wstring str);
	virtual long VirtualProtectEx(long hwnd, long addr, long size, long tpe, long old_protect);
};

#endif
