# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dmsoft_pb2 as dmsoft__pb2


class dmsoftServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDmsoftVersion = channel.unary_unary(
                '/dmsoft.dmsoftService/GetDmsoftVersion',
                request_serializer=dmsoft__pb2.GetDmsoftVersionRequest.SerializeToString,
                response_deserializer=dmsoft__pb2.GetDmsoftVersionResponse.FromString,
                )


class dmsoftServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDmsoftVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_dmsoftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDmsoftVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDmsoftVersion,
                    request_deserializer=dmsoft__pb2.GetDmsoftVersionRequest.FromString,
                    response_serializer=dmsoft__pb2.GetDmsoftVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dmsoft.dmsoftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class dmsoftService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDmsoftVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dmsoft.dmsoftService/GetDmsoftVersion',
            dmsoft__pb2.GetDmsoftVersionRequest.SerializeToString,
            dmsoft__pb2.GetDmsoftVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
