# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dmsoft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64msoft.proto\x12\x06\x64msoft\"\x19\n\x17GetDmsoftVersionRequest\"+\n\x18GetDmsoftVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t2h\n\rdmsoftService\x12W\n\x10GetDmsoftVersion\x12\x1f.dmsoft.GetDmsoftVersionRequest\x1a .dmsoft.GetDmsoftVersionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dmsoft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETDMSOFTVERSIONREQUEST._serialized_start=24
  _GETDMSOFTVERSIONREQUEST._serialized_end=49
  _GETDMSOFTVERSIONRESPONSE._serialized_start=51
  _GETDMSOFTVERSIONRESPONSE._serialized_end=94
  _DMSOFTSERVICE._serialized_start=96
  _DMSOFTSERVICE._serialized_end=200
# @@protoc_insertion_point(module_scope)
